config/routes.rb
Depts::Application.routes.draw do

  resources :depts, :members
  resources :depts do
    resources :members
  end

  root :to => 'depts#index'

end

app/models/dept.rb
class Dept < ActiveRecord::Base
  attr_accessible :name, :dept_id
  validates :name, :presence => true
  has_many :members
end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :name, :surname, :dept_id, :id
  belongs_to :dept
  validates :name, :surname, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/depts_controller.rb
class DeptsController < ApplicationController

  def index
    @depts = Dept.all

    respond_to do |format|
      format.html
      format.json { render :json => @depts }
    end
  end

  def show
    @dept = Dept.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @dept }
    end
  end

  def new
    @dept = Dept.new(params[:name])

    respond_to do |format|
      format.html
      format.json { render :json => @dept }
    end
  end

  def create
    @dept.new(params[:dept])

    respond_to do |format|
      if @dept.save
         format.html { redirect_to :action => 'index' }
         format.json { render :json => @dept }
      else
         format.html { render :action => 'new' }
         format.json { render :json => @dept }
      end
    end
  end

  def edit
    @dept = Dept.find(params[:id])
  end

  def update
    @dept = Dept.find(params[:id])

    respond_to do |format|
      if @dept.update_attributes(params[:dept])
         format.html { redirect_to :action => 'index'}#, :id => @dept }
         format.json { render :json => @dept }

      else
         format.html { redirect_to :action => 'edit' }
         format.json { render :json => @dept }
      end
    end
  end

  def destroy
    @dept = Dept.find(params[:id])
    @dept.destroy

    respond_to do |format|
      format.html { redirect_to :action => 'index' }
      format.json { render :json => @dept }
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    @dept = Dept.find(params[:dept_id])
    @members = @dept.members.all

    respond_to do |format|
      format.html
      format.json { render :json => @members }
    end
  end

  def show
    @dept = Dept.find(params[:dept_id])
    @member = @dept.member.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @member }
    end
  end

  def new
    @dept = Dept.find(params[:dept_id])
    @member = @dept.members.build

    respond_to do |format|
      format.html
      format.json { render :json => @member }
    end
  end

  def create
    @dept = Dept.find(params[:dept_id])
    @member = @dept.members.build(params[:member])

    respond_to do |format|
      if @member.save
          format.html { redirect_to dept url(@member.dept_id) }
          format.json { render :json => @member }
      else
          format.html { render :action => 'new' }
          format.json { render :json => @member }
      end
    end
  end

  def edit
    @dept = Dept.find(params[:dept_id])
    @member = @dept.members.find(params[:id])
  end

  def update
    @dept = Dept.find(params[:dept_id])
    @member = @dept.members.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
         format.html { redirect_to dept_url(@member.dept_id)}
         format.json { render :json => @member }

      else
         format.html { render :action => 'edit' }
         format.json { render :json => @member }
      end
    end
  end

  def destroy
    @dept = Dept.find(params[:dept_id])
    @member = @dept.members.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to dept_url(@member.dept_id) }
      format.json { render :json => @member }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/depts/_form.haml
= form_for(@dept) do |f|
  - if @dept.errors.any?
    #error_explanation
      %h2= pluralize(@dept.errors.count, "error")
      prohibited this from being saved:

      %ul
      - @dept.errors.full_messages.each do |msg|
        %li
          error
          = msg

  .field
    = f.label :Department
    %br
    = f.text_field :name

  .actions
    = f.submit "go"

app/views/depts/edit.haml
%h2= "Edit a department"

%p= render 'form'

%p= link_to "back", {:action => 'index' }

app/views/depts/index.haml
%h1 DEPARTMENTS

%ol
  - @depts.each do |d|
    %li= link_to d.name
    %p= link_to 'edit', edit_dept_path(d)
    %p= link_to 'get rid!', d, :method => :delete, :name => { :confirm => 'Are you sure?' }
    %p= link_to "add new", new_dept_path
    

app/views/depts/new.haml
%h2= "Add a new department"

%p= render 'form'

%p= link_to "back", {:action => 'index'}

app/views/depts/show.haml
%p= @dept.name

%p= link_to "back", {:action => 'index'}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/_form.haml
= form_for[@dept, @member] do |f|
  - if @member.errors.any?
    #error_explanation
      %h2= pluralize(@member.errors.count, "error"), dept_members_path(@dept)
      prohibited this from being saved:

      %ul
      - @member.errors.full_messages.each do |msg|
        %li
          error
          = msg

  .field
    = f.label :Name
    = f.text_field :name
    = f.label :Surname
    = f.text_field :surname

  .actions
    = f.submit "go"

app/views/members/edit.haml
%h2= "Edit a member"

%p= render 'form'

%p= link_to "back", {:action => 'index' }

app/views/members/index.haml
%h1 Members

%ol
  - @members.each do |m|
    %li= m.name
    %p= link_to 'edit', edit_dept_member_path(@dept, m)
    %p= link_to 'delete member!', [@dept, m], :method => :delete, :name => { :confirm => 'Are you sure?' }
    %p= link_to "add member", new_dept_member_path(@dept)

app/views/members/new.haml
%h2= "Add a new member"

%p= render 'form'

%p= link_to "back", {:action => 'index'}

app/views/members/show.haml
%p= @member.name

%p= link_to "back", {:action => 'index'}